//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int ID { get; set; }
        public int Account { get; set; }
        public int Group { get; set; }
    
        public virtual Account Account1 { get; set; }
        public virtual Group Group1 { get; set; }
    }
}
